bug fixes

diff --git a/src/usr/local/emhttp/plugins/cache-mover/scripts/cache_mover2 b/src/usr/local/emhttp/plugins/cache-mover/scripts/cache_mover2
--- a/src/usr/local/emhttp/plugins/cache-mover/scripts/cache_mover2
+++ b/src/usr/local/emhttp/plugins/cache-mover/scripts/cache_mover2
@@ -18,7 +18,7 @@ if [ "$unraid_syslog" == "yes" ]; then
 
 log_message() {
   while IFS= read -r line; do
-    logger "cache-mover: ${line}"
+    logger "cache-mover: reg: ${line}"
   done
 }
 exec > >(log_message) 2>&1
@@ -35,7 +35,7 @@ fi
 pool="${pool#/}"
 pool="${pool%/}"
 ################################
-tmp_openfiles="/usr/local/emhttp/plugins/cache-mover/tmp_openfiles3txt"
+tmp_openfiles="/usr/local/emhttp/plugins/cache-mover/tmp_openfiles3.txt"
 check_openfiles="/usr/local/emhttp/plugins/cache-mover/check_openfiles3.txt"
 
 ### rm openfiles
@@ -50,9 +50,12 @@ export LC_ALL=en_US.UTF-8
 ls -alrt /proc/[0-9]*/fd/* 2> /dev/null | grep -i "/disk" | grep -E "$subfolders" | grep -E "$filetypes" | sed '$!d' > $tmp_openfiles
 ### lookup openfile, abort if empty and rm temp openfiles
 if [ ! -s $tmp_openfiles ]; then
-	#echo "nothing played, aborting here"
-	rm $tmp_openfiles
-	exit;
+	ls -alrt /proc/[0-9]*/fd/* 2> /dev/null | grep -i "/$pool" | grep -E "$subfolders" | grep -E "$filetypes" | sed '$!d' > $tmp_openfiles
+	if [ ! -s $tmp_openfiles ]; then
+		#echo "nothing played, aborting here"
+		rm $tmp_openfiles
+		exit;
+	fi
 fi
 ### wait and look again (1 loop)
 if [ -s $tmp_openfiles ]; then
@@ -62,69 +65,88 @@ if [ -s $tmp_openfiles ]; then
 	sleep $wait_todo
 	### check open files on disks (checkup)
 	ls -alrt /proc/[0-9]*/fd/* 2> /dev/null | grep -i "/disk" | grep -E "$subfolders" | grep -E "$filetypes" | sed '$!d' > $tmp_openfiles
+	if [ ! -s $tmp_openfiles ]; then
+		ls -alrt /proc/[0-9]*/fd/* 2> /dev/null | grep -i "/$pool" | grep -E "$subfolders" | grep -E "$filetypes" | sed '$!d' > $tmp_openfiles
+		if [ ! -s $tmp_openfiles ]; then
+			#echo "nothing played, aborting here"
+			rm $tmp_openfiles
+			exit;
+		fi
+	fi
 fi
 ### check if file is still open
-if ! cmp --silent "$check_openfiles" "$tmp_openfiles"; then
-	echo "file changed during wait, exiting here"
-	exit;
+if [ -s $tmp_openfiles ]; then
+	if ! cmp --silent "$check_openfiles" "$tmp_openfiles"; then
+		echo "file changed during wait, exiting here"
+		exit;
+	fi
 fi
 ### fetch details and build pathes to progress
-shopt -s lastpipe
-cat $tmp_openfiles | while read tmp_openfile
-	do
-	openfile="/$(echo "${tmp_openfile#*/}")"
-	process_id=$(echo $openfile | awk '{ print $1; }' | cut -f 3 -d "/")
-	file_descr=$(echo $openfile | awk '{ print $1; }' | cut -f 5 -d "/")
-	openpath="$(readlink /proc/$process_id/fd/$file_descr)"
-	directory=$(dirname "$openpath")
-	filename=$(basename "$openpath")
-	diskname=$(echo $openpath | awk '{ print $1; }' | cut -f 3 -d "/")
-	if [ $diskname == "disks" ]; then
-		subdisk=$(echo $openpath | awk '{ print $1; }' | cut -f 4 -d "/")
-		diskname="$diskname/$subdisk"
+if [ -s $tmp_openfiles ]; then
+	shopt -s lastpipe
+	cat $tmp_openfiles | while read tmp_openfile
+		do
+		openfile="/$(echo "${tmp_openfile#*/}")"
+		process_id=$(echo $openfile | awk '{ print $1; }' | cut -f 3 -d "/")
+		file_descr=$(echo $openfile | awk '{ print $1; }' | cut -f 5 -d "/")
+		openpath="$(readlink /proc/$process_id/fd/$file_descr)"
+		directory=$(dirname "$openpath")
+		filename=$(basename "$openpath")
+		diskname=$(echo $openpath | awk '{ print $1; }' | cut -f 3 -d "/")
+		if [ $diskname == "disks" ]; then
+			subdisk=$(echo $openpath | awk '{ print $1; }' | cut -f 4 -d "/")
+			diskname="$diskname/$subdisk"
+		fi
+		poolpath=$(echo ${openpath/$diskname/$pool})
+		rsync_source=$(dirname "$openpath")
+		rsync_target=$(dirname "$poolpath")
+		done
+fi
+### check matches and exclusions
+if [ -s $tmp_openfiles ]; then
+	### break if there is no subfolder match
+	if [ ! -z "$subfolders" ]; then
+		if [[ $(cat $tmp_openfiles | grep -E "$subfolders") == "" ]]; then
+			echo "not matching $subfolders, breaking here"
+			exit;
+		fi
 	fi
-	poolpath=$(echo ${openpath/$diskname/$pool})
-	rsync_source=$(dirname "$openpath")
-	rsync_target=$(dirname "$poolpath")
-	done
-### break if there is no subfolder match
-if [ ! -z "$subfolders" ]; then
-	if [[ $(cat $tmp_openfiles | grep -E "$subfolders") == "" ]]; then
-		echo "not matching $subfolders, breaking here"
-		exit;
+	### break if there is no filetype match
+	if [ ! -z "$filetypes" ]; then
+		if [[ $(cat $tmp_openfiles | grep -E "$filetypes") == "" ]]; then
+			echo "not matching $filetypes, breaking here"
+			exit;
+		fi
+	fi
+	### break if there is a exclusion match
+	if [ ! -z "$exclusions" ]; then
+		if [[ ! $(cat $tmp_openfiles | grep -E "$exclusions") == "" ]]; then
+			echo "matching exclusion $exclusions, breaking here"
+			exit;
+		fi
 	fi
 fi
-### break if there is no filetype match
-if [ ! -z "$filetypes" ]; then
-	if [[ $(cat $tmp_openfiles | grep -E "$filetypes") == "" ]]; then
-		echo "not matching $filetypes, breaking here"
-		exit;
+### check cached file and update
+if [ -s $tmp_openfiles ]; then
+	### pool lookup and break after update access time
+	if [ -f "$poolpath" ]; then
+		echo "update access time: $rsync_target"
+		touch -a "$rsync_target"
+		directory=$(dirname "$rsync_target")
+		touch -a "$directory"
+#		exit;
 	fi
-fi
-### break if there is a exclusion match
-if [ ! -z "$exclusions" ]; then
-	if [[ ! $(cat $tmp_openfiles | grep -E "$exclusions") == "" ]]; then
-		echo "matching exclusion $exclusions, breaking here"
-		exit;
+	### pool only file and break after update access time
+	if [ -z "$openpath" ]; then
+		echo "update access time pool only dir: $directory"
+		touch -a "$directory"
+		directory=$(dirname "$directory")
+		touch -a "$directory"
+#		exit;
 	fi
-fi
-### pool lookup and break after update access time
-if [ -f "$poolpath" ]; then
-	echo "update access time: $rsync_target"
-	touch -a "$rsync_target"
-	directory=$(dirname "$rsync_target")
-	touch -a "$directory"
-	exit;
-fi
-### pool only file and break after update access time
-if [ -z "$openpath" ]; then
-	echo "update access time pool only dir: $directory"
-	touch -a "$directory"
-	directory=$(dirname "$directory")
-	touch -a "$directory"
-	exit;
 fi
 ### copy source files to target dir
+caching_done=""
 if [ ! -f "$poolpath" ]; then
 	if [ $rsync_mode == "file" ]; then
 		$rsync_copy "$openpath" "$poolpath"
@@ -134,6 +156,7 @@ if [ ! -f "$poolpath" ]; then
 	if [ "$unraid_note" = "yes" ]; then
 		/usr/local/emhttp/webGui/scripts/notify -e "Copy Note" -s "$rsync_target/" -i "normal" &
 	fi
+	caching_done="ok"
 fi
 ### add to mover tuning exclusion
 if [ "$move_excl" = "yes" ]; then
@@ -141,32 +164,39 @@ if [ "$move_excl" = "yes" ]; then
 	awk -i inplace '!seen[$0]++' $move_excl_list 2> /dev/null
 fi
 ### switch file descriptor
-### hard closing file descriptor path
-if [ "$switch_mode" = "close" ]; then
-	echo "$openpath/ open file will be closed"
-	fdclose $process_id $file_descr
-fi
-### hard switching file descriptor path
-if [ "$switch_mode" = "switch" ]; then
-	echo "open file $filename will be switched $pool now"
-	sleep 1
-	dst="$poolpath"
-	echo "$dst"
-	if gdb --version > /dev/null 2>&1; then
-		echo "ready to switch live"
-	else
-		echo "Unable to find gdb, check readme"
-		exit 1
+if [ "$caching_done" = "ok" ]; then
+	### hard closing file descriptor path
+	if [ "$switch_mode" = "close" ]; then
+		echo "$openpath/ open file will be closed"
+		fdclose $process_id $file_descr
 	fi
-	(
-	echo "attach $process_id"
-	echo 'call (int)open("'$dst'", 00|0100|02000, 0666)'
-	echo 'call (int)dup2($1,'$file_descr')'
-	echo 'call (int)close($1)'
-	echo 'detach'; echo 'quit'
-	) | gdb -q -x -
+	### hard switching file descriptor path
+	if [ "$switch_mode" = "switch" ]; then
+		echo "open file $filename will be switched $pool now"
+		sleep 1
+		dst="$poolpath"
+		echo "$dst"
+		if gdb --version > /dev/null 2>&1; then
+			echo "ready to switch live"
+		else
+			echo "Unable to find gdb, check readme"
+			exit 1
+		fi
+		(
+		echo "attach $process_id"
+		echo 'call (int)open("'$dst'", 00|0100|02000, 0666)'
+		echo 'call (int)dup2($1,'$file_descr')'
+		echo 'call (int)close($1)'
+		echo 'detach'; echo 'quit'
+		) | gdb -q -x -
+	fi
 fi
 ### update mover ignore list ###
 $listupdater
+## MediaServer Mode check
+if [ "$mediaserver_only" == "multi" ]; then
+	/usr/local/emhttp/plugins/cache-mover/scripts/cache_mover1
+	exit;
+fi
 
 exit;
